// constants.js
window.constants = {
  DEBUG: false,
  BATCH_SIZE: 50,
  MAX_FILE_SIZE_MB: 50,
  THUMBNAIL_BATCH_SIZE: 10,
  MAX_CONCURRENT_RENDERS: 1,
  MAX_MODELS_IN_MEMORY: 500,
  PAGE_SIZE: 100,
  DEFAULT_SORT: 'dateAdded DESC',
  RENDER_DELAY: 200,
  MAX_CONTEXT_USES: 20,
  MAX_CONTEXT_REUSE_COUNT: 100
};
